image: docker:latest

variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - deploy

before_script: 
  - docker-compose up -d
  - sleep 5

build: 
  tags: 
    - wiki
  stage: build
  script: 
    - docker-compose exec mkdocs /usr/local/bin/mkdocs build --clean
  only:
    - main

test: 
  tags: 
    - wiki
  stage: test
  script: 
    # build the mkdocs site
    - docker-compose exec mkdocs /usr/local/bin/mkdocs build
    - docker-compose exec mkdocs /usr/local/bin/mkdocs build --strict
    # output the usage page
    - docker-compose exec mkdocs /usr/local/bin/mkdocs 
    - sleep 5
    - curl -I http://localhost:8000
  
deploy:
  tags: 
    - wiki
  stage: deploy
  script:
    - docker login -u $REGISTRY_USER -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker tag mkdocs-rtd $CI_REGISTRY/nallen/systems-wiki/mkdocs-rtd:latest
    - echo "Deploying the site to the web server"
    - docker push $CI_REGISTRY/nallen/systems-wiki/mkdocs-rtd:latest
    
