# use dind to run the commands in the containers

#services: 
#  - docker:dind

stages:
  - build
  - test
  - deploy

#before_script: 
#  - docker-compose up -d
#  - sleep 5

# *** might need to use /usr/local/bin/mkdocs
build: 
  tags: 
    - wiki
  stage: build
  script: 
    - docker-compose exec mkdocs /usr/local/bin/mkdocs build --clean
  only:
    - main

test: 
  tags: 
    - wiki
  stage: test
  script: 
    # build the mkdocs site
    - docker-compose exec mkdocs /usr/local/bin/mkdocs build --clean
    # output the usage page
    - docker-compose exec mkdocs /usr/local/bin/mkdocs 
    - sleep 5
    - curl -I http://localhost:8000
  
deploy:
  tags: 
    - wiki
  stage: deploy
  script:
    - docker-compose up -d
    - docker-compose exec mkdocs mkdocs build --clean
    - echo "Deploying the site to the web server"
    
