version: '3'

services:
  mkdocs:
    image: squidfunk/mkdocs-material:latest
    volumes:
      - ./docs:/docs
    ports:
      - "8000:8000"
    command: ["mkdocs", "serve", "--dev-addr=0.0.0.0:8000"]