site_name: Systems Group Wiki

nav:
  - Home: index.md
  - About Us: about-us.md
  - Current Staff: current-staff.md
  - Our Services:
      - Linux/Unix Services: our-services/linux-unix.md
      - VPN Services: our-services/vpn.md
      - Computer Labs: our-services/computer-labs.md
      - Remote Z-Drive Access: our-services/remote-z-drive.md
      - Printing: our-services/printing.md

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages: 
        - yaml
        - shell
