site_name: Systems Group Wiki
nav:
  - About Us: about-us.md
  - Current Staff: current-staff.md
  - Our Services:
      - Linux/Unix Services: our-services/linux-unix.md
      - VPN Services: our-services/vpn.md
      - Computer Labs: our-services/computer-labs.md
      - Remote Z-Drive Access: our-services/remote-z-drive.md
      - Printing: our-services/printing.md
theme:
  name: material
  palette:
    scheme: slate
    primary: "slate"
    accent: "indigo"
  font:
    text: "Roboto"